export type MockCategory = {
  slug: string
  nameFa: string
  description: string
  productCount: number
  color: string     // برای placeholder و badge
  bgColor: string
}

export type MockProduct = {
  id: string
  slug: string
  sku: string
  nameFa: string
  categorySlug: string
  categoryName: string
  price: number
  comparePrice?: number
  rating: number
  reviewCount: number
  stock: number
  isFeatured: boolean
  isNew: boolean
  descriptionFa: string
  specs: { key: string; value: string }[]
  // رنگ placeholder برای نمایش قبل از تصویر واقعی
  placeholderFrom: string
  placeholderTo: string
}

// ─── دسته‌بندی‌ها ──────────────────────────────────────────────────────────────

export const mockCategories: MockCategory[] = [
  {
    slug: 'sensors',
    nameFa: 'حسگرها',
    description: 'حسگر حرکتی، مغناطیسی، شکست شیشه و دود',
    productCount: 18,
    color: '#3B82F6',
    bgColor: '#EFF6FF',
  },
  {
    slug: 'central-alarm',
    nameFa: 'دزدگیر مرکزی',
    description: 'پنل‌های اصلی و دستگاه‌های مرکزی حرفه‌ای',
    productCount: 9,
    color: '#E61010',
    bgColor: '#FFF1F1',
  },
  {
    slug: 'sirens',
    nameFa: 'سیرن و آژیر',
    description: 'سیرن داخلی، خارجی و پیزو با صدای بلند',
    productCount: 12,
    color: '#F97316',
    bgColor: '#FFF7ED',
  },
  {
    slug: 'control',
    nameFa: 'تجهیزات کنترل',
    description: 'ریموت، کی‌پد LCD و برد رله هوشمند',
    productCount: 14,
    color: '#10B981',
    bgColor: '#ECFDF5',
  },
  {
    slug: 'boosters',
    nameFa: 'تقویت‌کننده',
    description: 'آنتن و تقویت‌کننده سیگنال برای مسافت‌های طولانی',
    productCount: 6,
    color: '#8B5CF6',
    bgColor: '#F5F3FF',
  },
  {
    slug: 'accessories',
    nameFa: 'لوازم جانبی',
    description: 'کابل، منبع تغذیه، باتری و قطعات یدکی',
    productCount: 22,
    color: '#64748B',
    bgColor: '#F8FAFC',
  },
]

// ─── محصولات ──────────────────────────────────────────────────────────────────

export const mockProducts: MockProduct[] = [
  {
    id: '1',
    slug: 'bw-m100-pir-sensor',
    sku: 'BW-M100',
    nameFa: 'حسگر حرکتی PIR بیواز BW-M100',
    categorySlug: 'sensors',
    categoryName: 'حسگرها',
    price: 350_000,
    comparePrice: 430_000,
    rating: 4.8,
    reviewCount: 124,
    stock: 45,
    isFeatured: true,
    isNew: false,
    descriptionFa: 'حسگر حرکتی پیر با برد تشخیص ۱۲ متر و زاویه دید ۱۱۰ درجه. مناسب برای محیط‌های داخلی تا ۵۰ مترمربع.',
    specs: [
      { key: 'برد تشخیص', value: '۱۲ متر' },
      { key: 'زاویه دید', value: '۱۱۰ درجه' },
      { key: 'ولتاژ کاری', value: '۹-۱۶ ولت DC' },
      { key: 'دما', value: '-۱۰ تا +۵۰ درجه' },
    ],
    placeholderFrom: '#EFF6FF',
    placeholderTo: '#BFDBFE',
  },
  {
    id: '2',
    slug: 'bw-c500-central',
    sku: 'BW-C500',
    nameFa: 'دزدگیر مرکزی بیواز BW-C500 (۸ زون)',
    categorySlug: 'central-alarm',
    categoryName: 'دزدگیر مرکزی',
    price: 2_500_000,
    rating: 4.9,
    reviewCount: 89,
    stock: 12,
    isFeatured: true,
    isNew: false,
    descriptionFa: 'دزدگیر ۸ زون با قابلیت اتصال به ریموت، کی‌پد و پیام‌رسان. دارای باتری پشتیبان داخلی.',
    specs: [
      { key: 'تعداد زون', value: '۸ زون سیمی' },
      { key: 'ریموت', value: 'تا ۳۰ دستگاه' },
      { key: 'پیام‌رسان', value: 'GSM + PSTN' },
      { key: 'باتری پشتیبان', value: '۱۲V 7Ah' },
    ],
    placeholderFrom: '#FFF1F1',
    placeholderTo: '#FECACA',
  },
  {
    id: '3',
    slug: 'bw-s100-siren-outdoor',
    sku: 'BW-S100',
    nameFa: 'سیرن خارجی ضد آب بیواز BW-S100',
    categorySlug: 'sirens',
    categoryName: 'سیرن و آژیر',
    price: 450_000,
    comparePrice: 520_000,
    rating: 4.6,
    reviewCount: 67,
    stock: 30,
    isFeatured: true,
    isNew: true,
    descriptionFa: 'سیرن خارجی با صدای ۱۱۰ دسیبل، ضد آب IP65 و چراغ استروب LED.',
    specs: [
      { key: 'صدا', value: '۱۱۰ دسیبل' },
      { key: 'حفاظت', value: 'IP65' },
      { key: 'چراغ', value: 'استروب LED' },
      { key: 'رنگ', value: 'قرمز/سفید' },
    ],
    placeholderFrom: '#FFF7ED',
    placeholderTo: '#FED7AA',
  },
  {
    id: '4',
    slug: 'bw-r100-remote',
    sku: 'BW-R100',
    nameFa: 'ریموت ۴ کانال بیواز BW-R100',
    categorySlug: 'control',
    categoryName: 'تجهیزات کنترل',
    price: 250_000,
    rating: 4.7,
    reviewCount: 201,
    stock: 80,
    isFeatured: false,
    isNew: false,
    descriptionFa: 'ریموت ۴ کانال با فرکانس ۴۳۳ مگاهرتز و برد ۱۰۰ متر. سازگار با تمام دزدگیرهای بیواز.',
    specs: [
      { key: 'کانال', value: '۴ کانال' },
      { key: 'فرکانس', value: '۴۳۳ MHz' },
      { key: 'برد', value: 'تا ۱۰۰ متر' },
      { key: 'باتری', value: 'CR2032' },
    ],
    placeholderFrom: '#ECFDF5',
    placeholderTo: '#A7F3D0',
  },
  {
    id: '5',
    slug: 'bw-m200-magnetic',
    sku: 'BW-M200',
    nameFa: 'حسگر مغناطیسی در و پنجره BW-M200',
    categorySlug: 'sensors',
    categoryName: 'حسگرها',
    price: 120_000,
    rating: 4.5,
    reviewCount: 315,
    stock: 120,
    isFeatured: false,
    isNew: false,
    descriptionFa: 'حسگر مغناطیسی مخفی برای در و پنجره. نصب آسان با چسب دوطرفه یا پیچ.',
    specs: [
      { key: 'نوع', value: 'NO/NC' },
      { key: 'فاصله عملکرد', value: '۱.۵ سانتی‌متر' },
      { key: 'ابعاد', value: '۸۰×۱۵×۱۱ میلی‌متر' },
      { key: 'رنگ', value: 'سفید / قهوه‌ای' },
    ],
    placeholderFrom: '#EFF6FF',
    placeholderTo: '#BFDBFE',
  },
  {
    id: '6',
    slug: 'bw-c700-smart',
    sku: 'BW-C700',
    nameFa: 'دزدگیر هوشمند بیواز BW-C700 (WiFi + GSM)',
    categorySlug: 'central-alarm',
    categoryName: 'دزدگیر مرکزی',
    price: 3_800_000,
    comparePrice: 4_200_000,
    rating: 5.0,
    reviewCount: 43,
    stock: 7,
    isFeatured: true,
    isNew: true,
    descriptionFa: 'دزدگیر نسل جدید با اتصال WiFi+GSM، کنترل از راه دور از طریق اپلیکیشن و دوربین داخلی.',
    specs: [
      { key: 'اتصال', value: 'WiFi + GSM' },
      { key: 'تعداد زون', value: '۱۶ زون' },
      { key: 'اپلیکیشن', value: 'اندروید و iOS' },
      { key: 'دوربین', value: '۲MP داخلی' },
    ],
    placeholderFrom: '#FFF1F1',
    placeholderTo: '#FECACA',
  },
  {
    id: '7',
    slug: 'bw-k100-keypad',
    sku: 'BW-K100',
    nameFa: 'کی‌پد LCD بیواز BW-K100',
    categorySlug: 'control',
    categoryName: 'تجهیزات کنترل',
    price: 800_000,
    rating: 4.6,
    reviewCount: 58,
    stock: 22,
    isFeatured: false,
    isNew: false,
    descriptionFa: 'کی‌پد با نمایشگر LCD بک‌لایت، صفحه لمسی و قابلیت برنامه‌ریزی کامل.',
    specs: [
      { key: 'نمایشگر', value: 'LCD ۱۶×۲' },
      { key: 'تعداد کد', value: 'تا ۵۰ کد' },
      { key: 'زبان', value: 'فارسی / انگلیسی' },
      { key: 'بک‌لایت', value: 'آبی' },
    ],
    placeholderFrom: '#ECFDF5',
    placeholderTo: '#A7F3D0',
  },
  {
    id: '8',
    slug: 'bw-g100-glass-break',
    sku: 'BW-G100',
    nameFa: 'حسگر شکست شیشه بیواز BW-G100',
    categorySlug: 'sensors',
    categoryName: 'حسگرها',
    price: 420_000,
    rating: 4.4,
    reviewCount: 36,
    stock: 18,
    isFeatured: false,
    isNew: true,
    descriptionFa: 'حسگر آکوستیک تشخیص شکستن شیشه با برد ۶ متر. تنظیم حساسیت قابل تغییر.',
    specs: [
      { key: 'برد', value: '۶ متر' },
      { key: 'حساسیت', value: 'قابل تنظیم' },
      { key: 'انواع شیشه', value: 'معمولی، لمینت، سکوریت' },
      { key: 'ولتاژ', value: '۹-۱۶V DC' },
    ],
    placeholderFrom: '#EFF6FF',
    placeholderTo: '#BFDBFE',
  },
  {
    id: '9',
    slug: 'bw-s200-indoor-siren',
    sku: 'BW-S200',
    nameFa: 'سیرن داخلی پیزو بیواز BW-S200',
    categorySlug: 'sirens',
    categoryName: 'سیرن و آژیر',
    price: 180_000,
    rating: 4.3,
    reviewCount: 91,
    stock: 55,
    isFeatured: false,
    isNew: false,
    descriptionFa: 'سیرن پیزو داخلی با ۱۰۵ دسیبل صدا. مناسب برای فضاهای کوچک تا متوسط.',
    specs: [
      { key: 'صدا', value: '۱۰۵ دسیبل' },
      { key: 'ولتاژ', value: '۱۲V DC' },
      { key: 'جریان', value: '۴۰۰ میلی‌آمپر' },
      { key: 'ابعاد', value: '۸۸×۸۸×۴۲ میلی‌متر' },
    ],
    placeholderFrom: '#FFF7ED',
    placeholderTo: '#FED7AA',
  },
  {
    id: '10',
    slug: 'bw-a100-antenna',
    sku: 'BW-A100',
    nameFa: 'آنتن تقویت‌کننده سیگنال BW-A100',
    categorySlug: 'boosters',
    categoryName: 'تقویت‌کننده',
    price: 150_000,
    rating: 4.2,
    reviewCount: 29,
    stock: 40,
    isFeatured: false,
    isNew: false,
    descriptionFa: 'آنتن خارجی برای افزایش برد سیگنال دزدگیر در ساختمان‌های بزرگ یا با دیوار ضخیم.',
    specs: [
      { key: 'فرکانس', value: '۴۳۳ MHz' },
      { key: 'طول کابل', value: '۳ متر' },
      { key: 'بهره', value: '۵ dBi' },
      { key: 'اتصال', value: 'SMA Male' },
    ],
    placeholderFrom: '#F5F3FF',
    placeholderTo: '#DDD6FE',
  },
  {
    id: '11',
    slug: 'bw-sg100-smoke-gas',
    sku: 'BW-SG100',
    nameFa: 'حسگر دود و گاز ترکیبی BW-SG100',
    categorySlug: 'sensors',
    categoryName: 'حسگرها',
    price: 580_000,
    comparePrice: 680_000,
    rating: 4.9,
    reviewCount: 52,
    stock: 25,
    isFeatured: true,
    isNew: true,
    descriptionFa: 'حسگر ترکیبی دود و گاز با آلارم ۸۵ دسیبل. سنسور فتوالکتریک و الکتروکمیکال.',
    specs: [
      { key: 'تشخیص', value: 'دود + گاز CO' },
      { key: 'آلارم', value: '۸۵ دسیبل' },
      { key: 'باتری', value: '۹V + سیمی' },
      { key: 'عمر باتری', value: '۵ سال' },
    ],
    placeholderFrom: '#EFF6FF',
    placeholderTo: '#BFDBFE',
  },
  {
    id: '12',
    slug: 'bw-p100-power',
    sku: 'BW-P100',
    nameFa: 'منبع تغذیه پشتیبان ۱۲V/2A بیواز',
    categorySlug: 'accessories',
    categoryName: 'لوازم جانبی',
    price: 320_000,
    rating: 4.5,
    reviewCount: 144,
    stock: 60,
    isFeatured: false,
    isNew: false,
    descriptionFa: 'منبع تغذیه تثبیت‌شده ۱۲ ولت ۲ آمپر با قابلیت شارژ باتری پشتیبان و محافظت از اتصال کوتاه.',
    specs: [
      { key: 'خروجی', value: '۱۲V / 2A' },
      { key: 'باتری', value: 'تا ۷Ah' },
      { key: 'محافظت', value: 'اتصال کوتاه + اضافه ولتاژ' },
      { key: 'ورودی', value: '220V AC' },
    ],
    placeholderFrom: '#F8FAFC',
    placeholderTo: '#E2E8F0',
  },
]

export const featuredProducts = mockProducts.filter((p) => p.isFeatured)
export const newProducts = mockProducts.filter((p) => p.isNew)
