import { drizzle } from 'drizzle-orm/postgres-js'
import { migrate } from 'drizzle-orm/postgres-js/migrator'
import postgres from 'postgres'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'
import { existsSync, readdirSync } from 'fs'

const DATABASE_URL = process.env.DATABASE_URL

if (!DATABASE_URL) {
  console.warn('[migrate] ⚠️  DATABASE_URL not set — skipping migrations')
  process.exit(0)
}

const __dirname = dirname(fileURLToPath(import.meta.url))
const migrationsFolder = join(__dirname, 'migrations')

// Verify migrations folder exists and has content
if (!existsSync(migrationsFolder)) {
  console.error(`[migrate] ❌ Migrations folder not found: ${migrationsFolder}`)
  console.error('[migrate] ❌ Check Dockerfile COPY for migrations directory')
  process.exit(1)
}

const sqlFiles = readdirSync(migrationsFolder).filter(f => f.endsWith('.sql'))
console.log(`[migrate] Found ${sqlFiles.length} migration files in ${migrationsFolder}`)
if (sqlFiles.length === 0) {
  console.warn('[migrate] ⚠️  No .sql files found — nothing to migrate')
  process.exit(0)
}

console.log('[migrate] Connecting to database...')
const sql = postgres(DATABASE_URL, { max: 1, idle_timeout: 20, connect_timeout: 30 })
const db  = drizzle(sql)

try {
  console.log('[migrate] Running migrations...')

  // ── Fix poisoned __drizzle_migrations timestamps (one-time, idempotent) ──
  // Migrations 0000/0001 were generated by drizzle-kit while the machine's
  // clock was set far in the future: their journal "when" (1778500170046 /
  // 1778760609032, ≈2026) is LARGER than every legitimate migration after
  // them (0002-0022, all ≈2025). Drizzle's migrate() only ever compares
  // against the single most-recently-applied row's created_at, so once these
  // two rows were recorded, every migration added afterward — with a smaller,
  // correct timestamp — was silently skipped forever (this is why sms_logs,
  // product_variants, etc. never got created). Matched by exact hash (not a
  // timestamp threshold) so this can never touch any other migration.
  await sql`CREATE SCHEMA IF NOT EXISTS "drizzle"`
  await sql`
    CREATE TABLE IF NOT EXISTS "drizzle"."__drizzle_migrations" (
      id SERIAL PRIMARY KEY,
      hash text NOT NULL,
      created_at bigint
    )
  `
  const fixed = await sql`
    UPDATE "drizzle"."__drizzle_migrations"
    SET created_at = CASE hash
      WHEN 'b372900fb7c19b7a87496fccc3cebc54073dada08aa272d542cc0e045c65f530' THEN 1700000000000
      WHEN 'd24be7a4fe4b35e693eeaa3d18f13bdb237af63ef460fd7132e040cefbc99bac' THEN 1700000000001
    END
    WHERE hash IN (
      'b372900fb7c19b7a87496fccc3cebc54073dada08aa272d542cc0e045c65f530',
      'd24be7a4fe4b35e693eeaa3d18f13bdb237af63ef460fd7132e040cefbc99bac'
    ) AND created_at > 1748564400000
  `
  if (fixed.count > 0) {
    console.log(`[migrate] 🩹 Corrected ${fixed.count} poisoned migration timestamp(s) from a clock-skew bug`)
  }

  await migrate(db, { migrationsFolder })
  console.log('[migrate] ✅ All migrations applied successfully')
} catch (err) {
  console.error('[migrate] ❌ Migration FAILED:', err.message)
  if (err.cause) console.error('[migrate]    Cause:', err.cause)
  // Exit non-zero so entrypoint logs the warning, but app can still start
  // if tables already exist from a previous deploy
  process.exitCode = 1
} finally {
  await sql.end()
}
